force-app/main/default/objects/Webhook__c/Webhook__c.object-meta.xml
<CustomObject>
    <description>Used to post data to external systems</description>
    <label>Webhook</label>
    <nameField>
        <displayFormat>WH-{0000000000}</displayFormat>
        <label>Webhook Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webhook__c/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <description>Should the webhook execute synchronously or asynchronously?</description>
    <inlineHelpText>Choose asynchronous to generate a platform and send the webhook asynchronously. 
Choose synchronous to send the webhook immediately.</inlineHelpText>
    <label>Execution Order</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Web_Hook_Execution</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>The Request headers in JSON format.</description>
    <inlineHelpText>The Request headers in JSON format.</inlineHelpText>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The response or error message.</description>
    <inlineHelpText>The response or error message.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Object_Payload_Id__c.field-meta.xml
<CustomField>
    <fullName>Object_Payload_Id__c</fullName>
    <description>The id of the object to retrieve and post.</description>
    <label>Object Payload Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>The JSON Payload of the Webhook.</description>
    <inlineHelpText>The JSON Payload of the Webhook.</inlineHelpText>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the webhook.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Webhook_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>The Status code of the webhook request.</description>
    <inlineHelpText>The Status code of the webhook request.</inlineHelpText>
    <label>StatusCode</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The destination URL of the webhook.</description>
    <inlineHelpText>The destination URL of the webhook.</inlineHelpText>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/Webhook_Event__e.object-meta.xml
<CustomObject>
    <description>The event used to publish a webhook.</description>
    <label>Webhook Event</label>
    <pluralLabel>Webhook Events</pluralLabel>
    <!-- <publishBehavior>PublishImmediately</publishBehavior> -->
</CustomObject>

force-app/main/default/objects/Webhook_Event__e/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>The Request headers in JSON format.</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/Object_Payload_Id__c.field-meta.xml
<CustomField>
    <fullName>Object_Payload_Id__c</fullName>
    <description>The object id of the object to post. If this field is populated, the payload__c field is ignored.</description>
    <label>Object Payload Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>The JSON Payload of the Webhook. If object_payload_id__c is populated, this field is ignored.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The destination URL of the webhook.</description>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/Webhook_Id__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Id__c</fullName>
    <description>The SalesForce Id of the Webhook__c object.</description>
    <label>Webhook Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Web_Hook_Execution.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>IMMEDIATE</fullName>
        <default>true</default>
        <label>Immediate</label>
    </customValue>
    <customValue>
        <fullName>DELAYED</fullName>
        <label>Delayed</label>
    </customValue>
    <customValue>
        <fullName>ASYNCHRONOUS</fullName>
        <isActive>false</isActive>
        <label>ASYNCHRONOUS</label>
    </customValue>
    <customValue>
        <fullName>SYNCHRONOUS</fullName>
        <isActive>false</isActive>
        <label>SYNCHRONOUS</label>
    </customValue>
    <description>Should the webhook execute immediatly or be delayed?</description>
    <masterLabel>Web Hook Execution</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Webhook_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEW</fullName>
        <default>true</default>
        <label>NEW</label>
    </customValue>
    <customValue>
        <fullName>PROCESSED</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>EVENT CREATED</fullName>
    </customValue>
    <customValue>
        <fullName>RESUBMIT</fullName>
    </customValue>
    <description>The values used to represent a webhooks status</description>
    <masterLabel>Webhook Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WebhookFactory.cls
public without sharing class WebhookFactory {

    public static void generate_events_from_map(Map<Id, Webhook__c> my_webhook_map){
        List<Webhook_Event__e> events_to_publish = new List<Webhook_Event__e>();
        List<Webhook__c> webhooks_to_update = new List<Webhook__c>();

        for(Id webhook_id: my_webhook_map.keySet()){
            Webhook__c my_hook = my_webhook_map.get(webhook_id);
            if (my_hook.Execution_Order__c == 'IMMEDIATE' && (my_hook.Status__c == 'NEW' || my_hook.Status__c == 'RESUBMIT')) {
                
                events_to_publish.add(new Webhook_Event__e(
                    URL__c = my_hook.URL__c,
                    Headers__c = my_hook.Headers__c,
                    Payload__c = my_hook.Payload__c,
                    Webhook_Id__c = my_hook.Id
                ));
                Webhook__c my_new_hook = new Webhook__c(Id=my_hook.Id, Status__c = 'INPROGRESS');
                webhooks_to_update.add(my_new_hook);
            }
        }

        if ( !( webhooks_to_update.isEmpty() || events_to_publish.isEmpty() ) ){
            update webhooks_to_update;
            List<Database.SaveResult> results = EventBus.publish(events_to_publish);
        }
    }

    @future(callout=true)
    public static void make_callout_from_webhook(String webhook_id){
        
        
        Webhook__c my_webhook = [SELECT Id, Payload__c, Object_Payload_Id__c, Headers__c, URL__c, CreatedDate FROM Webhook__c WHERE Id =: webhook_id LIMIT 1];
        Map<String, String> header_map = (Map<String, String>)JSON.deserialize(my_webhook.Headers__c, Map<String, String>.class);

        HttpRequest req = new HttpRequest();
        for( String k: header_map.keySet() ){
            req.setHeader(k, header_map.get(k));
        }
        
        
        String final_payload = JSON.serialize(new WebhookBase(Datetime.valueOf(my_webhook.CreatedDate).format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX'), webhook_id));

        if (String.isBlank(my_webhook.Object_Payload_Id__c)){
            req.setBody(final_payload.replace('"REPLACE_TOKEN"', my_webhook.Payload__c));
        } else {
            String query_string = '';
            Schema.SObjectType token = Id.valueOf(my_webhook.Object_Payload_Id__c).getSObjectType();
            Schema.DescribeSObjectResult dr = token.getDescribe();
            for (String field: dr.fields.getMap().keySet())
                query_string += field + ', ';
            query_string = query_string.removeEnd(', ');
            SObject payload = Database.query('SELECT ' + query_string + ' FROM ' + dr.getName() + ' LIMIT 1');
            req.setBody(final_payload.replace('"REPLACE_TOKEN"', JSON.serialize(payload)));
        }
            
        req.setMethod('POST');
        req.setEndpoint( my_webhook.URL__c );

        Http my_http = new Http();
        Webhook__c my_webhook_obj = new Webhook__c();

        try {
            HTTPResponse res = my_http.send(req);
            my_webhook_obj.Id = webhook_id;
            my_webhook_obj.StatusCode__c = res.getStatusCode();
            my_webhook_obj.Status__c = res.getStatusCode() < 300 ? 'PROCESSED': 'FAILED';

            
        } catch(Exception e) {
            my_webhook_obj.Id= webhook_id;
            my_webhook_obj.Status__c = 'FAILED';
            my_webhook_obj.Message__c = e.getMessage();
        }

        update my_webhook_obj;
    }

}