force-app/main/default/objects/Webhook__c/Webhook__c.object-meta.xml
<CustomObject>
    <description>Used to post data to external systems</description>
    <label>Webhook</label>
    <nameField>
        <displayFormat>WH-{0000000000}</displayFormat>
        <label>Webhook Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webhook__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>The Request headers in JSON format.</description>
    <inlineHelpText>The Request headers in JSON format.</inlineHelpText>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>The JSON Payload of the Webhook.</description>
    <inlineHelpText>The JSON Payload of the Webhook.</inlineHelpText>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the webhook.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Webhook_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>The Status code of the webhook request.</description>
    <inlineHelpText>The Status code of the webhook request.</inlineHelpText>
    <label>StatusCode</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webhook__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The destination URL of the webhook.</description>
    <inlineHelpText>The destination URL of the webhook.</inlineHelpText>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Webhook_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NEW</fullName>
        <default>true</default>
        <label>NEW</label>
    </customValue>
    <customValue>
        <fullName>PROCESSED</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>EVENT CREATED</fullName>
    </customValue>
    <customValue>
        <fullName>RESUBMIT</fullName>
    </customValue>
    <description>The values used to represent a webhooks status</description>
    <masterLabel>Webhook Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Webhook_Test.cls
@isTest
global without sharing class Webhook_Test {

    global class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            switch on req.getEndpoint() {
                when 'https://www.good_response.com' {
                    res.setStatusCode(200);
                }
                when else {
                    res.setStatusCode(500);
                }
            }
            return res;
        }
    }

    @IsTest
    static void check_in_progress_request(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        Webhook__c my_request = new Webhook__c(
            URL__c = 'https://www.good_response.com',
            // Headers__c = '{"Content-Type": "application/json"}',
            Payload__c = '{"hello": "world"}'
        );

        insert my_request;
        Test.stopTest();
        Webhook__c my_completed_request = [SELECT Id, Status__c, StatusCode__c FROM Webhook__c WHERE Id =: my_request.Id LIMIT 1];

        System.assertEquals('INPROGRESS', my_completed_request.Status__c);
    }

    @IsTest
    static void check_after_event(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        Webhook__c my_request = new Webhook__c(
            URL__c = 'https://www.good_response.com',
            // Headers__c = '{"Content-Type": "application/json"}',
            Payload__c = '{"hello": "world"}'
        );

        insert my_request;
        Test.getEventBus().deliver();

        Test.stopTest();
        Webhook__c my_completed_request = [SELECT Id, Status__c, StatusCode__c FROM Webhook__c WHERE Id =: my_request.Id LIMIT 1];

        System.assertEquals('PROCESSED', my_completed_request.Status__c);
        System.assertEquals(200, my_completed_request.StatusCode__c);
    }

    @IsTest
    static void check_after_failed(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
        Webhook__c my_request = new Webhook__c(
            URL__c = 'https://www.good_responwwwwwwse.com',
            // Headers__c = '{"Content-Type": "application/json"}',
            Payload__c = '{"hello": "world"}'
        );

        insert my_request;
        Test.getEventBus().deliver();

        Test.stopTest();
        Webhook__c my_completed_request = [SELECT Id, Status__c, StatusCode__c FROM Webhook__c WHERE Id =: my_request.Id LIMIT 1];

        System.assertEquals('FAILED', my_completed_request.Status__c);
        System.assertEquals(500, my_completed_request.StatusCode__c);
    }

    @IsTest
    static void should_raise_exception(){
        
        Test.startTest();
        Webhook__c my_request = new Webhook__c(
            URL__c = 'https://www.good_responwwwwwwse.com',
            // Headers__c = '{"Content-Type": "application/json"}',
            Payload__c = '{"hello": "world"}'
        );

        insert my_request;
        Test.getEventBus().deliver();

        Test.stopTest();
        Webhook__c my_completed_request = [SELECT Id, Status__c, StatusCode__c FROM Webhook__c WHERE Id =: my_request.Id LIMIT 1];

        System.assertEquals('FAILED', my_completed_request.Status__c);
        System.assertEquals(null, my_completed_request.StatusCode__c);
    }

    @IsTest
    static void test_webhook_base_valid_check(){

        WebhookBase my_hook = new WebhookBase(Datetime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX'), '21123123123');

        my_hook.payload = 'e'.rightPad(131072, '0');
        System.assertEquals(false, my_hook.isValid());
        my_hook.payload = 'e'.rightPad(130877, '0'); // This pads the payload to mare the JSON string the max possible size.
        System.assert(my_hook.isValid(), 'Length is ' + String.valueOf(JSON.serialize(my_hook).length()));
    }
}