force-app/main/default/objects/Webhook_Event__e/Webhook_Event__e.object-meta.xml
<CustomObject>
    <description>The event used to publish a webhook.</description>
    <label>Webhook Event</label>
    <pluralLabel>Webhook Events</pluralLabel>
    <!-- <publishBehavior>PublishImmediately</publishBehavior> -->
</CustomObject>

force-app/main/default/objects/Webhook_Event__e/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>The Request headers in JSON format.</description>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>The JSON Payload of the Webhook. If object_payload_id__c is populated, this field is ignored.</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The destination URL of the webhook.</description>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webhook_Event__e/fields/Webhook_Id__c.field-meta.xml
<CustomField>
    <fullName>Webhook_Id__c</fullName>
    <description>The SalesForce Id of the Webhook__c object.</description>
    <label>Webhook Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebhookEventTriggerHandler.cls
public without sharing class WebhookEventTriggerHandler  extends TriggerHandler {

    private List<Webhook_Event__e> newList;
    private List<Webhook_Event__e> oldList;
    private Map<Id, Webhook_Event__e> oldMap;
    private Map<Id, Webhook_Event__e> newMap;

    @TestVisible static Boolean bypassTrigger = false;
    
    public WebhookEventTriggerHandler() {
        this.newList = (List<Webhook_Event__e>) Trigger.new;
        this.oldList = (List<Webhook_Event__e>) Trigger.old;
        this.oldMap = (Map<Id, Webhook_Event__e>) Trigger.oldMap;
        this.newMap = (Map<Id, Webhook_Event__e>) Trigger.newMap;
    }

    public override void afterInsert(){
        for (Webhook_Event__e webhook: this.newList){
            WebhookFactory.make_callout_from_webhook(webhook.URL__c, webhook.Headers__c, webhook.Payload__c, webhook.Webhook_Id__c);
        }
    }
}